 <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>fi.microserver</groupId>
	<artifactId>MicroServer</artifactId>
	<version>0.0.7-SNAPSHOT</version>
	<repositories>	
	<repository>
	  <id>com.teamdev</id>
	  <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
	</repository>
	</repositories>
	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
			</resource>
			<resource>
				<directory>src/main/resources-filtered</directory>
				<filtering>true</filtering>
			</resource>
		</resources>
		<plugins>
     <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <id>parse-version</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>parse-version</goal>
            </goals>
            <configuration>
            	<propertyPrefix>version</propertyPrefix>
            </configuration>
          </execution>
        </executions>
      </plugin>    
  			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<includeScope>runtime</includeScope>
						</configuration>
					</execution>
					<execution>
						<id>provision-copy</id>
						<phase>process-resources</phase>
						<goals><goal>copy</goal></goals>
						<configuration>
							<outputDirectory>target/classes</outputDirectory>
							<artifactItems>
								<artifactItem>
									<artifactId>MicroBoot</artifactId>
									<groupId>${project.groupId}</groupId>
									<version>${project.version}</version>
									<type>zip</type>
									<classifier>null</classifier>
									<destFileName>null.zip</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
			</plugin>
  	  <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <version>4.2.1</version>
 		<extensions>true</extensions>
        <configuration>
          <manifestLocation>target/classes</manifestLocation>
          <niceManifest>true</niceManifest>
          <instructions>
				<Embed-Dependency>*;scope=compile|runtime;inline=true</Embed-Dependency>
				<Private-Package>
					*.internal.*,
					com.teamdev.jxbrowser.deps.*,
					org.*,
					${jxbrowser.version},
					ch.*,
					fi.*
				</Private-Package>
          		<Export-Package>
          			!*.internal.*,
          			!*.deps.*,
          			!com.teamdev.protobuf.*,
          			org.osgi.service.provisioning;version="1.2.0";-noimport:=true,
           			com.teamdev.*;version="${jxbrowser.version}";-noimport:=true,
          			it.*;version="1.0.4";-noimport:=true
          		</Export-Package>
          		<Import-Package />
          </instructions>
        </configuration>
        <executions>
          <execution>
            <id>manifest</id>
            <phase>process-classes</phase>
            <goals>
              <goal>manifest</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
 			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifest>
							<useUniqueVersions>false</useUniqueVersions>
							<addClasspath>true</addClasspath>
							<mainClass>fi.microserver.Numworx</mainClass>
						</manifest>
					</archive>
				</configuration>
			</plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>copy-resources</id>
            <phase>package</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/target/dependency</outputDirectory>
              <resources>          
                <resource>
                  <directory>src/main/dwo</directory>
                  <include>numworx.dwo</include>
                  <filtering>true</filtering>
                </resource>
                <resource>
                	<directory>.</directory>
                	<include>all.policy</include>
                </resource>
              </resources>              
            </configuration>            
          </execution>
        </executions>
      </plugin>	</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>ch.jm.osgi.provisioning</artifactId>
			<version>0.9.1</version>
			<exclusions>
				<exclusion>
					<groupId>org.osgi</groupId>
					<artifactId>
						org.osgi.service.provisioning
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.framework</artifactId>
			<version>7.0.1</version>
		</dependency>
<!-- 	<dependency> -->
<!-- 	    	<groupId>com.teamdev.jxbrowser</groupId> -->
<!-- 	    	<artifactId>jxbrowser-${arch}</artifactId> -->
<!-- 	    	<version>${jxbrowser.version}</version> -->
<!-- 		</dependency> -->
<!-- 		<dependency> -->
<!-- 		    <groupId>com.teamdev.jxbrowser</groupId> -->
<!-- 		    <artifactId>jxbrowser-swing</artifactId> -->
<!-- 		    <version>${jxbrowser.version}</version> -->
<!-- 		</dependency> -->
		<dependency>
		    <groupId>it.sauronsoftware</groupId>
		    <artifactId>junique</artifactId>
		    <version>1.0.4</version>
		</dependency>
	</dependencies>
	<properties>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<fi.dwo.boot>http://cdn.dwo.nl/bundles/BootLoader-2.0.jar</fi.dwo.boot>
		<arch>mac</arch>
		<jxbrowser.version>7.13</jxbrowser.version>
		<security>#</security>
	</properties>
	<parent>
		<groupId>nl.uu.fi.dwo</groupId>
		<artifactId>DWO.master.pom</artifactId>
		<version>1.1</version>
	</parent>
	<profiles>
		<profile>
			<id>jxbrowser</id>
			<dependencies>
				<dependency>
				    <groupId>com.teamdev.jxbrowser</groupId>
				   	<artifactId>jxbrowser-${arch}</artifactId>
				   	<version>${jxbrowser.version}</version>
				</dependency>
				<dependency>
				    <groupId>com.teamdev.jxbrowser</groupId>
				    <artifactId>jxbrowser-swing</artifactId>
				    <version>${jxbrowser.version}</version>
				</dependency>
			</dependencies>
		</profile>
		<profile>
			<id>mac</id>
			<activation><os><family>mac</family></os></activation>
			<properties>
				<arch>mac</arch>
			</properties>
			<build>
				<plugins>
     			</plugins>
			</build>
		</profile>
		<profile>
			<id>linux</id>
			<activation><os><family>unix</family><name>Linux</name></os></activation>
			<properties>
				<arch>linux64</arch>
			</properties>
		</profile>	
		<profile>
			<id>windows</id>
			<activation><os><family>windows</family></os></activation>
			<properties>
				<arch>win64</arch>
			</properties>
			<build>
				<plugins>
     			</plugins>
			</build>	
		</profile>
		<profile>
			<id>assemble</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-assembly-plugin</artifactId>
						<configuration>
							<archive>
								<manifest>
									<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
									<addClasspath>false</addClasspath>
									<mainClass>fi.microserver.Numworx</mainClass>
								</manifest>
							</archive>
							<descriptorRefs>
								<descriptorRef>jar-with-dependencies</descriptorRef>
							</descriptorRefs>
						</configuration>
						<executions>
							<execution>
								<phase>package</phase>
								<goals>
									<goal>single</goal>
								</goals>
							</execution>
						</executions>
					</plugin>


				</plugins>
			</build>

		</profile>

	</profiles>
</project>
