<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.uu.fi.dwo</groupId>
    <artifactId>DWO.master.pom</artifactId>
    <version>1.1</version>
  </parent>
	<groupId>fi.dwo</groupId>
	<artifactId>fi.dwo.eawt</artifactId>
	<version>0.0.3-SNAPSHOT</version>
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<maven.compiler.compilerVersion>11</maven.compiler.compilerVersion>
		<maven.build.timestamp.format>yyyyMMddHHmm</maven.build.timestamp.format>
		<osgi.qualifier>${maven.build.timestamp}</osgi.qualifier>
	</properties>
	<packaging>bundle</packaging>
	<dependencies>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.core</artifactId>
			<version>6.0.0</version>
			<scope>provided</scope>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>2.5.3</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<_snapshot>${osgi.qualifier}</_snapshot>
						<Bundle-Activator>fi.dwo.eawt.impl.Activator</Bundle-Activator>
						<Export-Package>fi.dwo.eawt;version=1.0</Export-Package>
						<Import-Package>fi.dwo.eawt;version="[1,1.1)",*</Import-Package>
						<Require-Capability>osgi.ee; filter:="(&amp;(osgi.ee=JavaSE)(version=9))"</Require-Capability>
					</instructions>
				</configuration>
			</plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
            </plugin>
		</plugins>
	</build>
	<scm>
		<developerConnection>scm:svn:https://svn.science.uu.nl/repos/sci.velth101.projects/eawt/trunk</developerConnection>
	</scm>
	<name>EAWT</name>
</project>