javax.persistence.jdbc.url=${jdbc.dest}
javax.persistence.jdbc.driver=${jdbc.driver}
javax.persistence.jdbc.password=${jdbc.pw}
javax.persistence.jdbc.user=${jdbc.user}
eclipselink.ddl-generation=create-tables
eclipselink.ddl-generation.output-mode=database
flavor=${flavor}
