fi.dwo.profile: 77
fi.dwo.language: nl
fi.dwo.boot: ${fi.dwo.boot}
fi.dwo.target: DWO-docent
fi.microserver.version: ${project.version}
#fi.dwo.properties: true
#httpAuthentication=BASIC
serverUrlPath=https://app.dwo.nl/dwo/
jarUrlPath=http://cdn.dwo.nl/jars/
#appUrlPath=http://cdn.dwo.nl/apps/
resourceUrlPath=http://cdn.dwo.nl/resource
#for debugging
#fi.dwo.dwojapplet: file:///Users/wim/Documents/workspace-luna/DWOJApplet-Starter/target/DWOJApplet-Starter-2.0.jar
#fi.dwo.boot: file:///Users/wim/Documents/workspace-luna/BootLoader/target/BootLoader-2.0.jar
#fi.dwo.bundles: http://cdn.dwo.nl/bundles/
#fi.dwo.repository: file:///Users/wim/Documents/workspace-luna/MicroServer/target/index.xml