fi.dwo.profile: 1
fi.dwo.language: nl
#fi.dwo.codebase: http://cdn.dwo.nl/dwo/jars/
fi.dwo.codebase: file:/opt/dwo/webapps/war-shared/jars/
fi.dwo.properties: true
fi.dwo.boot: file:/Users/wim/Documents/workspace-luna/BootLoader/target/BootLoader-0.0.1-SNAPSHOT.jar
fi.dwo.dwojapplet:

httpAuthentication=BASIC
serverUrlPath=https://app.dwo.nl/dwo/
jarUrlPath=http://cdn.dwo.nl/jars
appUrlPath=http://cdn.dwo.nl/apps/
resourceUrlPath=http://cdn.dwo.nl/resource
