fi.dwo.profile: 77
fi.dwo.language: nl
fi.dwo.bundles: http://cdn.dwo.nl/bundles/
fi.dwo.boot: http://cdn.dwo.nl/bundles/BootLoader-0.0.1-SNAPSHOT.jar
fi.dwo.target: DWO-docent

fi.dwo.properties: false
httpAuthentication=BASIC
serverUrlPath=https://app.dwo.nl/dwo/
jarUrlPath=http://cdn.dwo.nl/jars
appUrlPath=http://cdn.dwo.nl/apps/
resourceUrlPath=http://cdn.dwo.nl/resource
