<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>nl.uu.fi.dwo</groupId>
	<artifactId>app-install</artifactId>
	<version>0.0.8-SNAPSHOT</version>
	<packaging>pom</packaging>
	<build>
		<extensions>
        <extension>
            <groupId>com.github.seahen</groupId>
            <artifactId>maven-s3-wagon</artifactId>
            <version>1.3.3</version>
        </extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh</artifactId>
				<version>2.8</version>
			</extension>
			<extension>
	            <groupId>io.github.qbast</groupId>
	            <artifactId>azure-storage-wagon</artifactId>
	            <version>1.0.1</version>
	        </extension>
		</extensions>
		<plugins>
        <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>2.6</version>
            <executions>
                <execution>
                    <id>copy-resources</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>copy-resources</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>${basedir}/target/</outputDirectory>
                        <resources>
                            <resource>
                                <directory>${basedir}/src/main/resources/</directory>
                                <includes>
                                    <include>*</include>
                                </includes>
                            </resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
   		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
					<execution>
						<id>provision-copy</id>
						<phase>process-resources</phase>
						<goals><goal>copy</goal></goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<artifactId>MicroBoot</artifactId>
									<groupId>fi.microserver</groupId>
									<version>1.0.0-SNAPSHOT</version>
									<type>zip</type>
									<classifier>null</classifier>
									<destFileName>null.zip</destFileName>
								</artifactItem>
							</artifactItems>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<includeScope>runtime</includeScope>
					<outputDirectory>${project.build.directory}</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-indexer-maven-plugin</artifactId>
				<version>3.3.0</version>
				<executions>
					<execution>
						<id>local-index</id>
						<goals>
							<goal>local-index</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<inputDir>target</inputDir>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>wagon-maven-plugin</artifactId>
				<version>1.0</version>
				<executions>
					<execution>
						<id>upload</id>
						<goals>
							<goal>upload</goal>
						</goals>
						<phase>${wagonPhase}</phase>
					</execution>
				</executions>
				<configuration>
					<fromDir>${project.build.directory}</fromDir>
					<includes>*</includes>
					<!-- <serverId>staff</serverId> -->
					<!-- <url>scp://gemini.science.uu.nl/home/staff/velth101/tmp</url> -->
					<serverId>prod</serverId>
					<url>${s3}</url>
					<toDir>bundles</toDir>
				</configuration>

			</plugin>

		</plugins>


	</build>
	<dependencies>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>DwoLoader</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>BootLoader</artifactId>
			<version>2.0.9-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.core</artifactId>
					<groupId>org.osgi</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.aries.async</groupId>
					<artifactId>
						org.apache.aries.async.promise.api
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>DWOJApplet-Starter</artifactId>
			<version>2.0.3-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.core</artifactId>
					<groupId>org.osgi</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.felix</groupId>
					<artifactId>
						org.apache.felix.bundlerepository
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.ops4j.pax.url</groupId>
			<artifactId>pax-url-wrap</artifactId>
			<version>2.6.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.configadmin</artifactId>
			<version>1.8.16</version>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.eventadmin</artifactId>
			<version>1.4.8</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.concierge</groupId>
			<artifactId>org.eclipse.concierge.shell</artifactId>
			<version>5.0.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.concierge</groupId>
					<artifactId>org.eclipse.concierge</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>unpack200</artifactId>
			<version>0.0.3-SNAPSHOT</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.sling/org.apache.sling.javax.activation -->
		<dependency>
		    <groupId>org.apache.sling</groupId>
		    <artifactId>org.apache.sling.javax.activation</artifactId>
		    <version>0.3.0</version>
		    <exclusions>
		    	<exclusion>
		    		<groupId>javax.activation</groupId>
		    		<artifactId>activation</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>fi.dwo.eawt</artifactId>
			<version>0.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.provisioning</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.log</artifactId>
			<version>1.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.event</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.cm</artifactId>
			<version>1.5.0</version>
		</dependency>
		<dependency>
		  <groupId>fi.beans</groupId>
		  <artifactId>numworxlf</artifactId>
		  <version>2.5.4</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>org.eclipse.equinox.http</artifactId>
			<version>1.0.500</version>
			<exclusions>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
    	  <groupId>nl.numworx.swingbrowser</groupId>
    	  <version>0.0.17-SNAPSHOT</version>
		  <artifactId>swingbrowser-ext</artifactId>
		  <exclusions>
		  	<exclusion>
		  		<groupId>junit</groupId>
		  		<artifactId>junit</artifactId>
		  	</exclusion>
		  	<exclusion>
		  		<groupId>javax.servlet</groupId>
		  		<artifactId>servlet-api</artifactId>
		  	</exclusion>
		  </exclusions>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.http</artifactId>
			<version>1.2.1</version>
		</dependency>
<!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api-osgi -->
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>${jxb}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser-swing</artifactId>
			<version>${jxb}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser-mac</artifactId>
			<version>${jxb}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser-mac-arm</artifactId>
			<version>${jxb}</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser-linux64</artifactId>
			<version>${jxb}</version>
		</dependency>
                <dependency>
                        <groupId>nl.numworx</groupId>
                        <artifactId>com.teamdev.jxbrowser-linux64-arm</artifactId>
                        <version>${jxb}</version>
                </dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser-win64</artifactId>
			<version>${jxb}</version>
		</dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <exclusions>
            	<exclusion>
            		<groupId>junit</groupId>
            		<artifactId>junit</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
 		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
			<version>1.7.21</version>
		</dependency>
        <dependency>
        	<groupId>org.osgi</groupId>
        	<artifactId>slf4j.osgi</artifactId>
        	<version>1.7.2</version>
        </dependency>
	</dependencies>
	<properties>
		<s3>s3://test-dwo-nl</s3>
		<jxb>7.28.1</jxb>
 		<wagonPhase>verify</wagonPhase>
	</properties>
	<profiles>
		<profile>
			<id>cds</id>
			<properties>
				<s3>s3://cds.dwo.nl</s3>
			</properties>
		</profile>
		<profile>
			<id>localhost</id>
			<properties>
				<s3>file://${user.home}/Public</s3>
			</properties>
		</profile>
		<profile>
			<id>deprecated</id>
			<dependencies>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.bundlerepository</artifactId>
			<version>2.0.10</version>
			<exclusions>
				<exclusion>
					<groupId>org.osgi</groupId>
					<artifactId>org.osgi.core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.easymock</groupId>
					<artifactId>easymock</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
			
			</dependencies>
		
		</profile>
	</profiles>
</project>
