<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
	  <groupId>nl.uu.fi.dwo</groupId>
	  <artifactId>runner-parent</artifactId>
	  <version>2.5.51-SNAPSHOT</version>
      <relativePath>../..</relativePath>
	</parent>
	<artifactId>app-install</artifactId>
	<packaging>war</packaging>
	<build>
		<finalName>bundles</finalName>
		<extensions>
        <extension>
            <groupId>com.github.seahen</groupId>
            <artifactId>maven-s3-wagon</artifactId>
            <version>1.3.3</version>
        </extension>
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh</artifactId>
				<version>2.8</version>
			</extension>
			<extension>
	            <groupId>io.github.qbast</groupId>
	            <artifactId>azure-storage-wagon</artifactId>
	            <version>1.0.1</version>
	        </extension>
		</extensions>
         <pluginManagement>
         	<plugins>
         		<plugin>
         			<artifactId>maven-war-plugin</artifactId>
         			<version>3.2.3</version>
         		</plugin>
         	</plugins>        
         </pluginManagement>
		<plugins>
        <plugin>
            <artifactId>maven-resources-plugin</artifactId>
            <version>2.6</version>
            <executions>
                <execution>
                    <id>copy-resources</id>
                    <phase>process-resources</phase>
                    <goals>
                        <goal>copy-resources</goal>
                    </goals>
                    <configuration>
                        <outputDirectory>${basedir}/target/</outputDirectory>
                        <resources>
                            <resource>
                                <directory>${basedir}/src/main/resources/</directory>
                                <includes>
                                    <include>*</include>
                                </includes>
                            </resource>
                        </resources>
                    </configuration>
                </execution>
            </executions>
        </plugin>
   		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<includeScope>runtime</includeScope>
					<outputDirectory>${project.build.directory}/${project.build.finalName}</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>biz.aQute.bnd</groupId>
				<artifactId>bnd-indexer-maven-plugin</artifactId>
				<version>3.3.0</version>
				<executions>
					<execution>
						<id>local-index</id>
						<goals>
							<goal>local-index</goal>
						</goals>
						<phase>prepare-package</phase>
						<configuration>
							<inputDir>${project.build.directory}/${project.build.finalName}</inputDir>
							<outputFile>${project.build.directory}/${project.build.finalName}/index.xml</outputFile>
							<indexFiles>
								<include>*.jar</include>
							</indexFiles>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>wagon-maven-plugin</artifactId>
				<version>1.0</version>
				<executions>
					<execution>
						<id>upload</id>
						<goals>
							<goal>upload</goal>
						</goals>
						<phase>${wagonPhase}</phase>
					</execution>
				</executions>
				<configuration>
					<fromDir>${project.build.directory}/${project.build.finalName}</fromDir>
					<includes>*</includes>
					<serverId>prod</serverId>
					<url>${s3}</url>
					<toDir>bundles</toDir>
				</configuration>

			</plugin>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<configuration>
					<packagingExcludes>WEB-INF/lib/**</packagingExcludes>
				</configuration>
				
			</plugin>

		</plugins>


	</build>
	<dependencies>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwoloader</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
		    <groupId>org.osgi</groupId>
		    <artifactId>org.osgi.service.repository</artifactId>
		    <version>1.1.0</version>
		</dependency>
<!-- repository 1.1 samen met promise 1.1 -->
		<dependency>
		    <groupId>org.osgi</groupId>
		    <artifactId>org.osgi.util.function</artifactId>
		    <version>1.1.0</version>
		    <optional>true</optional>
		</dependency>  
		<dependency>
		    <groupId>org.osgi</groupId>
		    <artifactId>org.osgi.util.promise</artifactId>
		    <version>1.1.1</version>
		    <optional>true</optional>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>bootloader</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.core</artifactId>
					<groupId>org.osgi</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.aries.async</groupId>
					<artifactId>
						org.apache.aries.async.promise.api
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>dwojapplet-starter</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<exclusions>
				<exclusion>
					<artifactId>org.osgi.core</artifactId>
					<groupId>org.osgi</groupId>
				</exclusion>
				<exclusion>
					<groupId>org.apache.felix</groupId>
					<artifactId>
						org.apache.felix.bundlerepository
					</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.ops4j.pax.url</groupId>
			<artifactId>pax-url-wrap</artifactId>
			<version>2.6.7</version>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.configadmin</artifactId>
			<version>1.8.16</version>
		</dependency>
		<dependency>
			<groupId>org.apache.felix</groupId>
			<artifactId>org.apache.felix.eventadmin</artifactId>
			<version>1.4.8</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.concierge</groupId>
			<artifactId>org.eclipse.concierge.shell</artifactId>
			<version>5.0.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.eclipse.concierge</groupId>
					<artifactId>org.eclipse.concierge</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>unpack200</artifactId>
			<version>2.5.48</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.sling/org.apache.sling.javax.activation -->
		<dependency>
		    <groupId>org.apache.sling</groupId>
		    <artifactId>org.apache.sling.javax.activation</artifactId>
		    <version>0.3.0</version>
		    <exclusions>
		    	<exclusion>
		    		<groupId>javax.activation</groupId>
		    		<artifactId>activation</artifactId>
		    	</exclusion>
		    </exclusions>
		</dependency>
		<dependency>
			<groupId>fi.dwo</groupId>
			<artifactId>fi.dwo.eawt</artifactId>
			<version>2.5.48</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.provisioning</artifactId>
			<version>1.2.0</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.log</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.event</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.cm</artifactId>
			<version>1.5.0</version>
		</dependency>
		<dependency>
		  <groupId>fi.beans</groupId>
		  <artifactId>numworxlf</artifactId>
		</dependency>
		<dependency>
			<groupId>nl.numworx.swingbrowser</groupId>
			<artifactId>org.eclipse.equinox.http</artifactId>
			<version>1.0.501</version>
			<exclusions>
				<exclusion>
					<groupId>javax.servlet</groupId>
					<artifactId>servlet-api</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
    	  <groupId>nl.numworx.swingbrowser</groupId>
    	  <version>0.0.21</version>
		  <artifactId>swingbrowser-ext</artifactId>
		  <exclusions>
		  	<exclusion>
		  		<groupId>junit</groupId>
		  		<artifactId>junit</artifactId>
		  	</exclusion>
		  	<exclusion>
		  		<groupId>javax.servlet</groupId>
		  		<artifactId>servlet-api</artifactId>
		  	</exclusion>
		  </exclusions>
		</dependency>
		<dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.http</artifactId>
			<version>1.2.1</version>
		</dependency>
<!-- https://mvnrepository.com/artifact/javax.xml.bind/jaxb-api-osgi -->
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.3.2</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<classifier>swing</classifier>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<classifier>mac</classifier>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<classifier>mac-arm</classifier>
		</dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<classifier>linux64</classifier>
		</dependency>
        <dependency>
            <groupId>nl.numworx</groupId>
            <artifactId>com.teamdev.jxbrowser</artifactId>
            <version>2.5.51-SNAPSHOT</version>
            <classifier>linux64-arm</classifier>
        </dependency>
		<dependency>
			<groupId>nl.numworx</groupId>
			<artifactId>com.teamdev.jxbrowser</artifactId>
			<version>2.5.51-SNAPSHOT</version>
			<classifier>win64</classifier>
		</dependency>
        <dependency>
            <groupId>com.googlecode.json-simple</groupId>
            <artifactId>json-simple</artifactId>
            <version>1.1.1</version>
            <exclusions>
            	<exclusion>
            		<groupId>junit</groupId>
            		<artifactId>junit</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
 		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-jdk14</artifactId>
			<version>1.7.21</version>
		</dependency>
        <dependency>
        	<groupId>org.osgi</groupId>
        	<artifactId>slf4j.osgi</artifactId>
        	<version>1.7.2</version>
        </dependency>
        <dependency>
		    <groupId>javax.cache</groupId>
		    <artifactId>cache-api</artifactId>
		    <version>1.1.1</version>
		    <optional>true</optional>
		</dependency>

        <dependency>
        	<groupId>nl.numworx.osgi</groupId>
        	<artifactId>ri-jcache</artifactId>
        	<version>2.5.49</version>
        	<exclusions>
        		<exclusion>
        			<groupId>org.jsr107.ri</groupId>
        			<artifactId>cache-ri-impl</artifactId>
        		</exclusion>
        	</exclusions>
        </dependency>
        <dependency>
        	<groupId>nl.numworx.toolloader</groupId>
        	<artifactId>toolloader</artifactId>
        	<version>2.5.51-SNAPSHOT</version>
        </dependency>
        <dependency>
			<groupId>org.osgi</groupId>
			<artifactId>org.osgi.service.async</artifactId>
			<version>1.0.0</version>
		</dependency>

	</dependencies>
 	<repositories>
 	    <repository>
	      <id>numworx-dwo-project</id>
	      <name>GitHub Packages DWO project</name>
	      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-dwo-project</url>
	      <snapshots>
			  <enabled>true</enabled>
		  </snapshots>
	    </repository>		
 	    <repository>
	      <id>numworx-vendor-jxbrowser</id>
	      <name>GitHub Packages Swingbrowser</name>
	      <url>https://maven.pkg.github.com/UtrechtUniversity/numworx-vendor-jxbrowser</url>
	      <snapshots>
			  <enabled>true</enabled>
		  </snapshots>
	    </repository>
	</repositories>
	<properties>
		<s3>s3://test-dwo-nl</s3>
		<jxb>${project.version}</jxb>
 		<wagonPhase>none</wagonPhase>
 		<maven.compiler.source>1.8</maven.compiler.source>
 		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
	<profiles>
		<profile>
			<id>cds</id>
			<properties>
				<s3>s3://cds.dwo.nl</s3>
				<wagonPhase>verify</wagonPhase>
			</properties>
		</profile>
		<profile>
			<id>localhost</id>
			<properties>
				<s3>file://${user.home}/Public</s3>
				<wagonPhase>verify</wagonPhase>
			</properties>
		</profile>
		<profile>
			<id>github</id>
			<properties>
			  <wagonPhase>none</wagonPhase>
			  <s3>file://${user.home}/not_used</s3>
			</properties>
		</profile>
	</profiles>
</project>
