<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>nl.numworx</groupId>
  <artifactId>initdb</artifactId>
    <parent>
	  <groupId>nl.uu.fi.dwo</groupId>
	  <artifactId>runner-parent</artifactId>
	  <version>2.5.49</version>
    </parent>
    <dependencies>
		<dependency>
		    <groupId>org.redisson</groupId>
		    <artifactId>redisson</artifactId>
		    <version>3.22.1</version>
		</dependency>
		<dependency>
			<groupId>nl.uu.fi.dwo</groupId>
			<artifactId>dwoserver</artifactId>
			<classifier>classes</classifier>
			<exclusions>
				<exclusion>
					<groupId>org.jsr107.ri</groupId>
					<artifactId>cache-ri-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
        <dependency>
		  <groupId>software.amazon.jdbc</groupId>
  		  <artifactId>aws-advanced-jdbc-wrapper</artifactId>
  		  <version>2.3.7</version>
        </dependency>
       <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.4.0</version>
            <!--comment scope for elastic beanstalk-->
            <scope>runtime</scope>
            <exclusions>
            	<exclusion>
            		<groupId>com.google.protobuf</groupId>
            		<artifactId>protobuf-java</artifactId>
            	</exclusion>
            </exclusions>
        </dependency>
 		<dependency>
		    <groupId>org.postgresql</groupId>
		    <artifactId>postgresql</artifactId>
		    <version>42.7.11</version>
		</dependency>
				<dependency>
    				<groupId>nl.uu.fi.dwo.rest</groupId>
					<artifactId>redis-config</artifactId>
					<version>2.5.48</version>
				</dependency>
		</dependencies>
    <properties>
        <jdbc.driver>com.mysql.cj.jdbc.Driver</jdbc.driver>
        <jdbc.dest>jdbc:mysql://127.0.0.1:3306/dwocopy?allowPublicKeyRetrieval=true&amp;useSSL=false</jdbc.dest>
        <jdbc.user>root</jdbc.user>
        <jdbc.pw>test</jdbc.pw>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <flavor>MYSQL</flavor>
    </properties>
    <build>
		<resources>
			<resource>
				<filtering>true</filtering>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
	              <plugin>
                        <artifactId>maven-jar-plugin</artifactId>
                        <version>2.4</version>
                        <configuration>
                                <archive>
                                        <manifest>
        			                <mainClass>nl.numworx.initdb.Main</mainClass>
                                                <addClasspath>true</addClasspath>
                                                <useUniqueVersions>false</useUniqueVersions>
                                        </manifest>
                                </archive>
                        </configuration>
                      </plugin>
			<plugin>
       			<groupId>org.codehaus.mojo</groupId>
        		<artifactId>exec-maven-plugin</artifactId>
        		<version>3.6.2</version>
        		<executions>
	          		<execution>
		            	<goals>
		              		<goal>java</goal>
		            	</goals>
	          		</execution>
        		</executions>
        		<configuration>
	          		<mainClass>nl.numworx.initdb.Main</mainClass>
         		</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>postgress</id>
			<properties>
		        <jdbc.driver2>org.postgresql.Driver</jdbc.driver2>
	        	<jdbc.copy>jdbc:postgresql://localhost:5432/dwocopy</jdbc.copy>
	        	<flavor>POSTGRES</flavor>
			</properties>
		</profile>
		<profile>
			<id>external</id>
			<build>
				<plugins>
				<plugin>
			        <groupId>org.codehaus.mojo</groupId>
			        <artifactId>properties-maven-plugin</artifactId>
			        <version>1.2.1</version>
			        <executions>
			          <execution>
			            <phase>initialize</phase>
			            <goals>
			              <goal>read-project-properties</goal>
			            </goals>
			            <configuration>
			              <urls>
			                <file>file:///${env.HOME}/copydb.properties</file>
			              </urls>
			            </configuration>
			          </execution>
			        </executions>
			      </plugin>
				</plugins>			
			</build>
		</profile>
	</profiles>
</project>
