fi.dwo.profile: 77
fi.dwo.language: nl
fi.dwo.boot0: ${fi.dwo.boot}
fi.dwo.target: DWO-docent
fi.microserver.version: ${project.version}
com.teamdev.jxbrowser.version: ${jxbrowser.version}
#fi.dwo.properties: true
#dwo_env: test
#httpAuthentication=BASIC
serverUrlPath=https://app.dwo.nl/dwo/
jarUrlPath=http://cdn.dwo.nl/jars/
#appUrlPath=http://cdn.dwo.nl/apps/
resourceUrlPath=http://cdn.dwo.nl/resource
#for debugging
#fi.dwo.dwojapplet: file:///Users/wim/Documents/workspace-luna/DWOJApplet-Starter/target/DWOJApplet-Starter-2.0.jar
#fi.dwo.boot: file:///Users/wim/workspace-oxygen/BootLoader/target/BootLoader-2.1.jar
fi.dwo.bundles: http://cdn.dwo.nl/bundles/
fi.dwo.repository: http://cdn.dwo.nl/bundles/index.xml
#fi.dwo.bundles: http://test-dwo-nl.s3.amazonaws.com/bundles/
#fi.dwo.repository: http://test-dwo-nl.s3.amazonaws.com/bundles/index.xml
#fi.dwo.repository: file:///Users/wim/workspace-oxygen/app-install/target/index.xml
#fi.dwo.bundles: file:///Users/wim/workspace-oxygen/app-install/target/

#fi.dwo.dwojapplet.domain.DWO: file:///Users/wim/workspace-oxygen/DWOJClient/target/DWOJClient-2.2.6-SNAPSHOT-jar-with-dependencies.jar
#fi.dwo.boot0: file:///home/velth101/workspace-oxygen/BootLoader/target/BootLoader-2.0.jar

org.osgi.framework.security=${security}
