<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>nl.numworx</groupId>
  <artifactId>com.teamdev.jxbrowser</artifactId>
  <version>7.28.1</version>
  <repositories>
  <repository>
    <id>com.teamdev</id>
    <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
  </repository>
  </repositories>
  <dependencies>
	<!-- https://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd -->
	<dependency>
    	<groupId>biz.aQute.bnd</groupId>
	    <artifactId>biz.aQute.bnd</artifactId>
	    <version>6.3.1</version>
	</dependency>
      <dependency>
          <groupId>com.teamdev.jxbrowser</groupId>
          <artifactId>jxbrowser-cross-platform</artifactId>
          <type>pom</type>
          <version>7.28.1</version>
      </dependency>
      <dependency>
          <groupId>com.teamdev.jxbrowser</groupId>
          <artifactId>jxbrowser-swing</artifactId>
          <version>7.28.1</version>
      </dependency>
  </dependencies>
  <build>
      <plugins>
   		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<phase>generate-resources</phase>
					</execution>
				</executions>
				<configuration>
					<includeScope>runtime</includeScope>
					<outputDirectory>${project.build.directory}</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
        		<artifactId>exec-maven-plugin</artifactId>
        		<version>3.6.2</version>
        		<executions>
          			<execution>
            			<goals>
              				<goal>exec</goal>
            			</goals>
            			<phase>compile</phase>
          			</execution>
        		</executions>
        		<configuration>
          		  <executable>sh</executable>
		          <workingDirectory>${project.basedir}</workingDirectory>
		          <arguments>
		            <argument>go.sh</argument>
		          </arguments>
		          <environmentVariables>
		          </environmentVariables>
		        </configuration>
			</plugin>
      </plugins>
  </build>
  
  <packaging>pom</packaging>
</project>
