<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>nl.uu.fi.dwo</groupId>
    <artifactId>runner-parent</artifactId>
    <version>2.5.50</version>
  </parent>
  <groupId>nl.numworx</groupId>
  <artifactId>com.teamdev.jxbrowser</artifactId>
  <repositories>
  <repository>
    <id>com.teamdev</id>
    <url>https://europe-maven.pkg.dev/jxbrowser/releases</url>
  </repository>
  </repositories>
  <dependencies>
	<!-- https://mvnrepository.com/artifact/biz.aQute.bnd/biz.aQute.bnd -->
	<dependency>
    	<groupId>biz.aQute.bnd</groupId>
	    <artifactId>biz.aQute.bnd</artifactId>
	    <version>6.3.1</version>
	    <optional>true</optional>
	</dependency>
      <dependency>
          <groupId>com.teamdev.jxbrowser</groupId>
          <artifactId>jxbrowser-cross-platform</artifactId>
          <type>pom</type>
          <version>7.28.1</version>
          <optional>true</optional>
      </dependency>
      <dependency>
          <groupId>com.teamdev.jxbrowser</groupId>
          <artifactId>jxbrowser-swing</artifactId>
          <version>7.28.1</version>
          <optional>true</optional>
      </dependency>
  </dependencies>
  <build>
      <plugins>
   		<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>2.10</version>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<phase>generate-resources</phase>
					</execution>
				</executions>
				<configuration>
					<includeScope>runtime</includeScope>
					<outputDirectory>${project.build.directory}</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
        		<artifactId>exec-maven-plugin</artifactId>
        		<version>3.6.2</version>
        		<executions>
          			<execution>
            			<goals>
              				<goal>exec</goal>
            			</goals>
            			<phase>compile</phase>
          			</execution>
        		</executions>
        		<configuration>
          		  <executable>sh</executable>
		          <workingDirectory>${project.basedir}</workingDirectory>
		          <arguments>
		            <argument>go.sh</argument>
		            <argument>${project.version}</argument>
		          </arguments>
		          <environmentVariables>
		          </environmentVariables>
		        </configuration>
			</plugin>
			<plugin>
				<artifactId>maven-install-plugin</artifactId>
				<configuration>
					<groupId>nl.numworx</groupId>
					<artifactId>com.teamdev.jxbrowser</artifactId>
					<version>${project.version}</version>
					<packaging>jar</packaging>
				</configuration>
				<executions>
					<execution>
					   <goals><goal>install-file</goal></goals>
					   <phase>install</phase>
					   <configuration>
					   		<file>target/com.teamdev.jxbrowser-7.28.1.jar</file>
					   </configuration>
					</execution>
                    <execution>
					   <id>swing</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-swing-7.28.1.jar</file>
							<classifier>swing</classifier>
                        </configuration>
                    </execution>
                    <execution>
					   <id>win64</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-win64-7.28.1.jar</file>
							<classifier>win64</classifier>
                        </configuration>
                    </execution>
                    <execution>
					   <id>linux64</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-linux64-7.28.1.jar</file>
							<classifier>linux64</classifier>
                        </configuration>
                    </execution>
                    <execution>
					   <id>linux64-arm</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-linux64-arm-7.28.1.jar</file>
							<classifier>linux64-arm</classifier>
                        </configuration>
                    </execution>
                    <execution>
					   <id>mac</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-mac-7.28.1.jar</file>
							<classifier>mac</classifier>
                        </configuration>
                    </execution>
                    <execution>
					   <id>mac-arm</id>
                       <goals><goal>install-file</goal></goals>
                       <phase>install</phase>
                       <configuration>
                            <file>target/com.teamdev.jxbrowser-mac-arm-7.28.1.jar</file>
							<classifier>mac-arm</classifier>
                        </configuration>
                    </execution>
			    </executions>
			 </plugin>
      </plugins>
  </build>
  
  <packaging>pom</packaging>
</project>
