<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
          <groupId>nl.uu.fi.dwo</groupId>
          <artifactId>runner-parent</artifactId>
          <version>2.5.50-SNAPSHOT</version>
	</parent>
	<groupId>fi.microserver</groupId>
	<artifactId>osgi-parent</artifactId>
	<packaging>pom</packaging>
	<modules>
<!--    	<module>unpack200</module>-->
		<module>BootLoader</module>
		<module>DWOJApplet-Starter</module>
		<module>app-install</module>
<!--		<module>dwoloader</module>-->
<!--		<module>ri-jcache</module>-->
		<module>toolloader</module>
	</modules>
	<build>
		<plugins>
			<plugin>
				<groupId>external.atlassian.jgitflow</groupId>
				<artifactId>jgitflow-maven-plugin</artifactId>
				<version>1.0-m5.1</version>
				<configuration>
					<!-- see goals wiki page for configuration options -->
					<flowInitContext>
						<developBranchName>develop</developBranchName>
						<masterBranchName>main</masterBranchName>
					</flowInitContext>
					<localOnly>false</localOnly>
					<allowSnapshots>false</allowSnapshots>
					<enableSshAgent>true</enableSshAgent>
					<noDeploy>true</noDeploy>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.jcraft</groupId>
						<artifactId>jsch</artifactId>
						<version>0.1.54</version>
					</dependency>
					<dependency>
						<groupId>net.java.dev.jna</groupId>
						<artifactId>jna-platform</artifactId>
						<version>5.12.1</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>
</project>
