profile: 65
jar: http://webcluster.fi.uu.nl/dwo/jars/dwo.jar
;jar: http://dwo.fi.uu.nl/dwo/jars/dwo.jar
main-class: fi.dwo.client.domain.DWO
param.1: -l
param.2: nl
param.3: -s
param.4: http://webcluster.fi.uu.nl/servlet/fi.dwo.server.persistence.DbAccessLdapServlet
;param.3: -s
;param.4: http://dwo.fi.uu.nl/dwo/dbaccess
;param.5: -r
;param.6: http://dwo.fi.uu.nl/dwo/resources
;username:
;password:
;limitedSchoolAccess:true
;schoolAccessProperties: http://dwo.fi.uu.nl/gr/schools.properties