profile: 1
jar: http://localhost:8080/dwo/jars/dwo.jar
main-class: fi.dwo.client.domain.DWO
param.1: -s
param.2: http://localhost:8080/dwo/dbaccess
;param.3: -r
;param.4: http://localhost:8080/dwo/resources
;username: mieke
;password: passw