profile: 1
jar: https://app.dwo.nl/dwo/jars/dwo.jar
main-class: fi.dwo.client.domain.DWO
param.1: -l
param.2: nl
param.3: -s
param.4: https://app.dwo.nl/dwo/dsaccess
param.5: -r
param.6: https://app.dwo.nl/dwo/resources
;username:
;password:
;limitedSchoolAccess:true
;schoolAccessProperties: http://dwo.fi.uu.nl/gr/schools.properties